# Generated by Django 4.1.4 on 2023-02-08 17:02

from django.db import migrations, models
import django.db.models.deletion
import lists.models


class Migration(migrations.Migration):

    dependencies = [
        ("lists", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="list",
            name="date",
        ),
        migrations.RemoveField(
            model_name="list",
            name="description",
        ),
        migrations.AlterField(
            model_name="list",
            name="title",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, max_length=300)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("date", models.DateField(default=lists.models.expiry)),
                (
                    "list",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="lists.list"
                    ),
                ),
            ],
        ),
    ]
