# Generated by Django 4.1.4 on 2023-02-09 17:06

from django.db import migrations, models
import django.db.models.deletion
import lists.models


class Migration(migrations.Migration):

    dependencies = [
        ("lists", "0003_alter_item_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="ToDoItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, max_length=300)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("due_date", models.DateField(default=lists.models.expiry)),
            ],
            options={
                "ordering": ["due_date"],
            },
        ),
        migrations.RenameModel(
            old_name="List",
            new_name="ToDoList",
        ),
        migrations.DeleteModel(
            name="Item",
        ),
        migrations.AddField(
            model_name="todoitem",
            name="todo_list",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="lists.todolist"
            ),
        ),
    ]
